version: '3'
services:
  odoo:
    image: odoo:15
    build: ./
    depends_on:
      - db
    volumes:
      - ./data/odoo:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    ports:
      - "8069:8069"

  db:
    image: postgres:13
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    expose:
      - "5432"
